### ISSUE TITLE
hi bro,How do you realize the collision detection between the pointelockcontrols perspective and the wall?

### ISSUE THREAD

**Issue by nikonikoCW** [joppiesaus/mazegame#2]
I currently use gltf model and pointelockcontrols, want to realize roaming in a house

**Comment by joppiesaus** [comment]
Greetings! ehm, basically, whenever the player want to walk, I have a raycaster casting a ray forward right in the front of the player. Then I check with `raycaster.intersectObjects( [ wallMesh ] )` what is in front of it. If it is too close, I do not allow the player to go walk further. I'd assume you could do this too, except with your mesh of your house. Figuring out the direction involves some trigonometry. Really, you'd have to look at the code( 
https://github.com/joppiesaus/mazegame/blob/master/js/mazegame.js#L313 https://github.com/joppiesaus/mazegame/blob/master/js/pointerlock.js)
The collision detection could be improved, probably by doing two raycasts at each side so that the player cannot see through walls if they are really in a skewed position, and the pointerlock implementation is quite old, but it works.

Have a great day!

**Comment by joppiesaus** [comment]
Also, you can look at the pointerlockcontrols example from threejs(https://threejs.org/examples/?q=pointerlock#misc_controls_pointerlock)

**Comment by nikonikoCW** [comment]
thk，bro

**Comment by joppiesaus** [comment]
no problem :)
